@startuml MDD
skinparam style strictuml
hide methods
hide empty members
title Wordle - Diagramme de composants

package "Reduced State" {
  class AppState {
    mots: string[];
    correctLetters: string[];
    almostCorrectLetters: string[];
    wrongLetters: string[];
    answer: string;
    currentWordIndex: number;
    hasWon: boolean;
    numberOfTries: number;
  }
}

package "Actions" {
  class Actions {
    setAnswer: string
    setWord: string
    addCorrectLetter: string
    addAlmostLetter: string
    addWrongLetter: string
    setWordIndex: number
    setHasWon: boolean
    setNumberOfTries: number
    resetAttempt: void
  }
}

package "Components" {
  class LettreClavier {
    lettre: char
  }

  class BackButtonClavier {
    caractere: char
  }

  class EnterButtonClavier {
    caractere: char
  }

  class Clavier {
    rows: RowClavier[]
  }

  class RowClavier {
    lettres: LettreClavier[]
    backButton?: BackButtonClavier
    enterButton?: EnterButtonClavier
  }

  class LettreAffichage {
    lettre: char
    couleur: Color
  }

  class RowAffichage {
      lettres: LettreAffichage[]
  }

  class GrilleAffichage {
      row: RowAffichage[]
  }

  class Details {
      answer: string
      numberOfTries: number
  }
}

GrilleAffichage "1" -down- "5" RowAffichage : Contient >
RowAffichage "1" -down- "5" LettreAffichage : Contient >
Clavier "1" -down- "3" RowClavier: Contient >
RowClavier "1" -down- "26" LettreClavier: Contient >
RowClavier "1" -down- "0..1" BackButtonClavier: Contient >
RowClavier "1" -down- "0..1" EnterButtonClavier: Contient >
Components -up- Actions: Dispatch >
Actions -right- "Reduced State": Gets reduced >
Components -down- "Reduced State": < Reads

@enduml
